# Background and foreground colors
background = #151e23
background-opacity = 0.90
foreground = #f5e6de

# Standard colors
palette = 0=#010609
palette = 1=#fa7578
palette = 2=#8edac5
palette = 3=#f5e6de
palette = 4=#f5e6de
palette = 5=#f5e6de
palette = 6=#8edac5
palette = 7=#eddcc8

# Bright colors
palette = 8=#7c98a1
palette = 9=#fc98ab
palette = 10=#8edac5
palette = 11=#f5e6de
palette = 12=#f5e6de
palette = 13=#f5e6de
palette = 14=#8edac5
palette = 15=#f5e6de

window-padding-color = extend-always

