# This file is not a full hyprland configuration.
# It is intended to be included in your main hyprland.conf.

$activeBorderColor = rgba(eddcc8ee)

general {
    col.active_border = $activeBorderColor
}
